name: latentspace
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.0 # nvidia canal necessário para utilizar gpu
  - torchvision
  - torchaudio
  - cudatoolkit=11.5
  - pytorch-lightning #1.4.9 # projeto do encoder
  - torchmetrics
  - numpy=1.24
  - wandb
  - opencv=4.7 # pip install opencv-contrib-python (Need to import cv2)
  - pandas
  - albumentations
  - GitPython
  - scikit-image
  - scikit-learn
  - scipy
  - matplotlib
  - seaborn
  - pillow
  - pyyaml
  - git
  - pip
  - plotly
  - xlsxwriter
  # pip install fft-conv-pytorch