program: models_sweep.py
method: bayes
name: Null
metric:
  name: Loss/Val
  goal: minimize
  name: MAE/Val/Epoch
  goal: minimize
  name: MAPE/Val/Epoch
  goal: minimize
parameters:
  lr:
    max: 0.0001
    min: 0.0000000000001
  gradient_clip:
    min: 0.1
    max: 0.6
  batch_size:
    max: 128
    min: 32